// Bakes fidelity data into the engine: real city coordinates (for geo-pins) and
// a curated, vetted icon set (Lucide). Both come from real sources so the engine
// never improvises geography or icon paths. Run: npx tsx scripts/bake-fidelity.ts
import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const require = createRequire(import.meta.url);

// ── Cities: top N by population from all-the-cities (real coordinates) ──
type City = { name: string; population: number; loc: { coordinates: [number, number] } };
const cities = require("all-the-cities") as City[];
const top = [...cities].sort((a, b) => b.population - a.population).slice(0, 220);
const coords: Record<string, [number, number]> = {};
for (const c of top) {
  const key = c.name.toLowerCase();
  if (!coords[key]) coords[key] = [
    Math.round(c.loc.coordinates[0] * 100) / 100,
    Math.round(c.loc.coordinates[1] * 100) / 100,
  ];
}

// ── Icons: curated business/deck subset from lucide-static (vetted paths) ──
const WANT = [
  "shield", "zap", "activity", "trending-up", "trending-down", "globe", "map-pin",
  "users", "user", "building", "building-2", "briefcase", "target", "check",
  "circle-check", "x", "triangle-alert", "lock", "lock-open", "eye", "search",
  "filter", "layers", "database", "server", "cloud", "cpu", "settings",
  "refresh-cw", "send", "mail", "calendar", "clock", "dollar-sign", "credit-card",
  "shopping-cart", "package", "truck", "rocket", "lightbulb", "sparkles", "star",
  "heart", "flag", "compass", "route", "git-branch", "workflow", "bell",
  "message-square", "file-text", "folder", "link", "arrow-right", "arrow-up-right",
  "plus", "minus", "bar-chart", "chart-bar", "chart-line", "chart-pie",
];
const icons: Record<string, string> = {};
const missing: string[] = [];
for (const name of WANT) {
  try {
    const svg = await readFile(
      resolve(repoRoot, "node_modules/lucide-static/icons", `${name}.svg`),
      "utf8",
    );
    const inner = svg.replace(/<!--[\s\S]*?-->/g, "").match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
    if (inner) icons[name] = inner[1].replace(/\s+/g, " ").trim();
    else missing.push(name);
  } catch {
    missing.push(name);
  }
}

const out = `// AUTO-GENERATED by scripts/bake-fidelity.ts — do not edit by hand.
// Real city coordinates (all-the-cities, top by population) + vetted Lucide icon
// paths. The engine composes geography and icons ONLY from these — never from
// model-recalled coordinates or hand-drawn SVG.
export const CITY_COORDS: Record<string, [number, number]> = ${JSON.stringify(coords)};
export const ICONS: Record<string, string> = ${JSON.stringify(icons)};
`;
await writeFile(resolve(repoRoot, "engine/fidelity-data.ts"), out, "utf8");
console.log(
  `Baked ${Object.keys(coords).length} cities + ${Object.keys(icons).length} icons → engine/fidelity-data.ts` +
    (missing.length ? `\n  skipped (not in lucide-static): ${missing.join(", ")}` : ""),
);
